### ISSUE TITLE
Скролл в чате накладывается на блоки с сообщениями

### ISSUE THREAD

**Issue by redveronika** [shyr1punk/conf#1]
@shyr1punk

Кажется, что у блока `chat__messages` не хватает отступа справа, чтобы при появлении скролла, он не перекрывал сами сообщения.

![Скриншот](https://user-images.githubusercontent.com/17981464/31886678-0c0a57fc-b7fe-11e7-85f7-e4aadd7e4124.jpg)

**Comment by shyr1punk** [comment]
Спасибо, посмотрим.

**Comment by shyr1punk** [comment]
Лучше поздно, чем никогда: исправили

![photo_2018-06-06_11-05-25](https://user-images.githubusercontent.com/2280073/41025055-8e863070-6979-11e8-91cc-77e697e81d5e.jpg)

**Comment by shyr1punk** [comment]
Исправили то давно, вот только я не написал :)

**Comment by redveronika** [comment]
@shyr1punk ура! Хорошо, что написал:)
